### ISSUE TITLE
Beta/release version confusion (Suggestions)

### ISSUE THREAD

**Issue by colin-marshall** [jcm93/jmc#15]
As I'm testing things out here, it is getting hard to know which version of the program I have downloaded and installed for a few reasons:

- When I go to "about" it always says 1.0 even though you're on 0.2 beta 3, so I have no way of knowing which version is actually on my system. Please keep the in-app version # in line with the releases on GitHub.
- Also, releasing multiple revisions under the same version name (0.2 beta 2 for example had 3 updates) is rather confusing because on the Releases page the date remains the same even though it was updated. Would be nice if the beta # was just incremented with every update.
- Also, why not just _always_ include the debug symbols while you are in beta? I wouldn't exactly consider the application stable at this point (sorry if this sounds critical) so it's just one less download/upload for you and your users.

Thanks for all your hard work!

**Comment by jcm93** [comment]
Thanks for the suggestions, and for filing all these issues. Don't worry about coming off as critical!

You are correct, I need to get my act together with versioning and updating, particularly in-app. I will probably go with the many-releases approach instead of updating the releases in-place from here on.

Including debug symbols was an Xcode issue; now that I've figured out how to do it they will be included in all testing releases.

**Comment by colin-marshall** [comment]
That's great! Thanks for listening.
