### ISSUE TITLE
Files not removed from library when deleted

### ISSUE THREAD

**Issue by jakes44** [jcm93/jmc#29]
I converted some of my flac library to mp3, and they were auto-added to my jmc library (as per the settings/folder I told it to watch). However, after moving those files to my phone and then deleting them from my machine, jmc still shows them in the library just as unable to locate.

**Comment by jakes44** [comment]
Am looking into it

**Comment by jcm93** [comment]
I think this is intended behavior. There isn't a good way to know whether a file going missing or being deleted is intentional or not, and since the program wants to err on the side of not losing your data, I don't think it should remove tracks unless you do so explicitly. Let me know if you think differently.

**Comment by jakes44** [comment]
Maybe I'm just missing a setting? Is there a way to remove tracks from library as of now? I can't seem to find it...

**Comment by jakes44** [comment]
If so, then there is no issue to resolve.

**Comment by jcm93** [comment]
Oh, selecting them and pressing Delete should do the trick. Let me know if it isn't. I should probably add a menu item for that...

**Comment by jakes44** [comment]
That did it... Issue closed, unless you think I should look into auto removing files from library when not located? Maybe a toggle?
