### ISSUE TITLE
No main library window on start of app

### ISSUE THREAD

**Issue by colin-marshall** [jcm93/jmc#5]
I get no GUI on startup of the app. I only get the menus in the top menubar. I can open preferences and edit those but there's no main window displaying an empty library.

macOS version: El Capitan 10.11.6

**Comment by jcm93** [comment]
This bug was caused by an issue with Core Data's autogenerated accessors for mutating ordered sets, which the program does on startup with library organization templates and source list items. For some reason the issue only appears on 10.11.

Commits 4d8a784 and 10742f9 fix the issue. A new build incorporating these changes will be out soon.

Also, 1241b84 implements a proper window manager for when the main window is otherwise closed/lost.
